Repository OpenTekHub/otpauthentication, pull requests merged in 2025-07, with the labels that each got.

#21 added neon db with sqlalchemy + psycorg
  app/main.py
  app/models/database.py
  app/models/user.py
  app/routers/otp.py
  requirements.txt
Labels: gssoc2025, level3

#24 Adding github templates for Issues and PRs
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, gssoc2025, level2

#25 Create Readme
  Readme
Labels: gssoc2025, level1
